language: ruby
rvm:
  - 2.3.4
  - 2.4.1
  - rbx-2
  - ruby-head
  - jruby-head

# jruby-head sometimes breaks stuff, but it's passing at the moment
#matrix:
#  allow_failures:
#    - rvm: jruby-head

branches:
  only:
    - master
