language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - rbx-2
  - ruby-head
  - jruby-head

# jruby-head sometimes breaks stuff, but it's passing at the moment
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2

branches:
  only:
    - master
