require "active_support/hash_with_indifferent_access"
require "activerecord-postgres-hstore/railties"
require "activerecord-postgres-hstore/string"
require "activerecord-postgres-hstore/hash"
require "activerecord-postgres-hstore/coder"
